repos:
  - repo: local
    hooks:
      # Prevent committing .rej files (left behind by `copier update` /
      # patch conflicts). Forces the contributor to resolve them.
      - id: forbidden-files
        name: forbidden files
        entry: found rejection files; review them and remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix, --indent=2]
        # The committed OpenAPI spec is large and machine-formatted by
        # `scripts/postman_to_openapi.jl` (or `openapi-generator`); leave it.
        exclude: "^spec/openapi\\.json$"
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint-fix
        # `docs/src/api/**.md` is generated by the VitepressDocs plugin
        # (one page per OpenAPI tag, with one heading per operation).
        # Two operations with identical `summary:` produce two H2s of
        # the same text — fixing that means editing the spec, not the
        # markdown. Skip the gate there.
        exclude: "^docs/src/api/"
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ericphanson/ExplicitImports.jl
    rev: v1.15.0
    hooks:
      - id: explicit-imports
        name: ExplicitImports checks
        # The CLI walks every nested module under `Project.toml`, so we
        # can't physically exclude `src/api/` (it's a submodule of the
        # main package). Instead we run only the checks that the
        # codegen output cannot violate by construction:
        #   - no_stale_explicit_imports — catches dead imports anywhere
        #   - no_self_qualified_accesses — catches `Pkg.foo` calls from
        #     inside `Pkg` itself
        # The other checks (no_implicit_imports, all_*_via_owners,
        # all_*_are_public) trip on generated `using OpenAPI` lines and
        # internal references like `OpenAPI.APIClientImpl`. `--print`
        # still surfaces those as informational output in CI logs.
        args:
          - --print
          - --checklist
          - exclude_no_implicit_imports,exclude_all_explicit_imports_via_owners,exclude_all_explicit_imports_are_public,exclude_all_qualified_accesses_via_owners,exclude_all_qualified_accesses_are_public
  - repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v2.0.1
    hooks:
      - id: runic
        # Runic re-formats Julia source files. Generated `src/api/` is
        # owned by openapi-generator; reformatting it would diverge from
        # what `gen/regenerate.jl` produces and break the round-trip.
        exclude: "^src/api/"
  - repo: https://github.com/crate-ci/typos
    rev: v1.40.1
    hooks:
      - id: typos
